# Generated by Django 4.1 on 2023-07-30 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_is_encadrant_customuser_is_encadrant_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="date_requested",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="encadrant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
