# Generated by Django 4.1 on 2023-07-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_verificationrequest_date_requested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="date_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
