# Generated by Django 4.1 on 2023-07-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_verificationrequest_date_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
