# Generated by Django 4.1.3 on 2023-08-01 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_verificationrequest_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_intern_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
